import CatalogGenerator
import CryptoKit
import Foundation
import Testing

/// Holds the committed catalogs equal to the bytes that ``CatalogGenerator``
/// writes from the skill folders (marketplace.md 3.3 and 3.6 step 3).
///
/// The catalogs are generated, thus nobody edits them by hand. A skill that is
/// added, dropped, or renamed without a run of `scripts/generate-catalogs`
/// fails this suite, and thus fails CI, instead of reaching a user as a catalog
/// that does not name the skill.
@Suite("Catalog sync")
struct CatalogSyncTests {
    /// The name of the file of a skill. A folder of the layer root is a skill
    /// when it holds this file.
    private static let skillFileName = "SKILL.md"

    /// The name of the file that holds the release version of the catalogs.
    private static let versionFileName = "VERSION"

    /// The opening text of the `digest` of a discovery index entry.
    private static let digestPrefix = "sha256:"

    /// The format of one byte of a digest: two lower-case hexadecimal digits.
    private static let digestByteFormat = "%02x"

    /// The one plugin that the Claude catalog holds (marketplace.md 3.3).
    private static let expectedPluginCount = 1

    /// The path of one skill folder, as the Claude catalog writes it.
    ///
    /// - Parameter name: The name of the skill.
    /// - Returns: The path, relative to the source of the plugin.
    private static func pluginSkillPath(name: String) -> String {
        "./skills/\(name)"
    }

    /// The URL of the `SKILL.md` of one skill, as the discovery index writes
    /// it.
    ///
    /// - Parameter name: The name of the skill.
    /// - Returns: The URL, relative to the root of the site.
    private static func indexSkillURL(name: String) -> String {
        "/skills/\(name)/\(skillFileName)"
    }

    /// The files that the generator writes from the checked-in skill folders.
    ///
    /// - Returns: One entry for each generated file.
    /// - Throws: An error when the generator cannot read the repository.
    private static func generatedFiles() throws -> [GeneratedCatalogFile] {
        try CatalogGenerator(repositoryRoot: RepositoryLayout.repositoryRoot()).generate()
    }

    /// Reads one committed file of the repository.
    ///
    /// - Parameter path: The path of the file, relative to the repository root.
    /// - Returns: The bytes of the file.
    /// - Throws: An error when the file is not there, or cannot be read.
    private static func committedFile(atPath path: String) throws -> Data {
        try Data(contentsOf: RepositoryLayout.repositoryRoot().appendingPathComponent(path))
    }

    /// The names of the skill folders on disk, which is the truth that every
    /// catalog reports.
    ///
    /// The walk keeps a direct child of the layer root that holds a `SKILL.md`
    /// file, thus it skips `_partials/` in the same way discovery skips it.
    ///
    /// - Returns: The names, in sorted order.
    /// - Throws: An error when the layer root cannot be read.
    private static func skillFolderNames() throws -> [String] {
        let root = RepositoryLayout.skillsRoot()
        let children = try FileManager.default.contentsOfDirectory(at: root, includingPropertiesForKeys: nil)
        return
            children
            .filter { FileManager.default.fileExists(atPath: $0.appendingPathComponent(skillFileName).path) }
            .map(\.lastPathComponent)
            .sorted()
    }

    /// The `sha256:` digest of one file, computed here rather than taken from
    /// the generator.
    ///
    /// - Parameter url: The file to read.
    /// - Returns: The digest, in the form the discovery index writes.
    /// - Throws: An error when the file cannot be read.
    private static func digest(ofFileAt url: URL) throws -> String {
        let bytes = try Data(contentsOf: url)
        let hexadecimal = SHA256.hash(data: bytes).map { String(format: digestByteFormat, $0) }.joined()
        return digestPrefix + hexadecimal
    }

    /// Every committed catalog file holds the bytes that the generator writes
    /// now.
    ///
    /// A missing file also fails here, because the read of the committed file
    /// throws.
    @Test("Every committed catalog file holds the generated bytes")
    func committedCatalogsAreCurrent() throws {
        for file in try Self.generatedFiles() {
            let committed = try Self.committedFile(atPath: file.path)
            #expect(
                committed == file.contents,
                "\(file.path) is not the same as the generator output. Run scripts/generate-catalogs.")
        }
    }

    /// The generator writes the same bytes each time it runs.
    ///
    /// Thus a second run of `scripts/generate-catalogs` changes no file, and a
    /// difference in the working tree is always a difference of the library.
    @Test("The generator writes the same bytes on a second run")
    func generationIsDeterministic() throws {
        let first = try Self.generatedFiles()
        let second = try Self.generatedFiles()
        #expect(first == second)
    }

    /// The one plugin of the Claude catalog lists every skill folder one time.
    @Test("The Claude plugin lists every skill folder exactly once")
    func claudePluginListsEverySkillOnce() throws {
        let catalog = try JSONDecoder().decode(
            ClaudeCatalog.self, from: Self.committedFile(atPath: ClaudeCatalog.path))
        #expect(catalog.plugins.count == Self.expectedPluginCount)
        let plugin = try #require(catalog.plugins.first)
        let expected = try Self.skillFolderNames().map(Self.pluginSkillPath)
        #expect(plugin.skills == expected)
        #expect(Set(plugin.skills).count == plugin.skills.count)
    }

    /// The discovery index names every skill folder, and each entry carries the
    /// URL and the digest of its own `SKILL.md`.
    @Test("Each discovery index entry carries the digest of its SKILL.md")
    func indexDigestsMatchTheSkillFiles() throws {
        let index = try JSONDecoder().decode(
            DiscoveryIndex.self, from: Self.committedFile(atPath: DiscoveryIndex.path))
        let names = try Self.skillFolderNames()
        #expect(index.skills.map(\.name) == names)
        for entry in index.skills {
            let file = RepositoryLayout.skillsRoot()
                .appendingPathComponent(entry.name)
                .appendingPathComponent(Self.skillFileName)
            let digest = try Self.digest(ofFileAt: file)
            #expect(entry.url == Self.indexSkillURL(name: entry.name))
            #expect(entry.digest == digest)
        }
    }

    /// The release version of the Claude catalog is the `VERSION` file, which
    /// is the one source of the version.
    @Test("The Claude catalog version is the VERSION file")
    func catalogVersionIsTheVersionFile() throws {
        let catalog = try JSONDecoder().decode(
            ClaudeCatalog.self, from: Self.committedFile(atPath: ClaudeCatalog.path))
        let text = try String(decoding: Self.committedFile(atPath: Self.versionFileName), as: UTF8.self)
        #expect(catalog.metadata.version == text.trimmingCharacters(in: .whitespacesAndNewlines))
    }
}
